CREATE VIEW full_invoice_view AS
SELECT
  i.InvoiceID,
  i.ShipID,
  i.ShipName,
  i.ShipWeight,
  
  i.AgentID,
  i.AgentNameAr,
  i.AgentNameEn,
  i.ServiceType,
  i.ServiceTypeName,
  i.ServiceTypeFactor,
  i.InvoiceDate,
  i.InvoiceDateT,
  i.ArrivalDate,
  i.ArrivalDateT,
  i.DepartureDate,
  i.DepartureDateT,
  i.PeriodDays,
  i.MSericeBathPrice,
  i.AnchorageEntry,
  i.AnchorageEntryT,
  i.AnchorageLeave,
  i.AnchorageLeaveT,
  i.AnchorageDays,
  i.MSericeAnchoragePrice,
  i.MovePort1,
  i.MovePort2,
  i.MovePort3,
  i.MovePortPrice,
  i.TripNo,
  i.DockingNo,
  i.RouteNo,
  i.ShiftedNo,
  i.Reason,
  i.MSFraction1,
  i.MSFraction2,
  i.MSFraction3,
  i.MService1,
  i.MService2,
  i.MService3,
  i.MSericeInPrice,
  i.MSericeOutPrice,
  i.MSTOTAL, 
  
   
  s1.code AS SScode1,
  s1.Description AS Description1, 
  i.SSName1,
  i.SSUnit1,
  i.SSQut1,
  i.SSPrice1,
  i.SSNote1,
  i.SSUPrice1,
  s2.code AS SScode2,
  s2.Description AS Description2, 
  i.SSName2,
  i.SSUnit2,
  i.SSQut2,
  i.SSPrice2,
  i.SSNote2,
  i.SSUPrice2,
  s3.code AS SScode3,
  s3.Description AS Description3, 
  i.SSName3,
  i.SSUnit3,
  i.SSQut3,
  i.SSPrice3,
  i.SSNote3,
  i.SSUPrice3,
  s4.code AS SScode4,
  s4.Description AS Description4, 
  i.SSName4,
  i.SSUnit4,
  i.SSQut4,
  i.SSPrice4,
  i.SSNote4,
  i.SSUPrice4,
  s5.code AS SScode5,
  s5.Description AS Description5,  
  i.SSUnit5,
  i.SSQut5,
  i.SSName5,
  i.SSNote5,
  i.SSUPrice5,
  i.SSPrice5,
  
  i.SSTOTAL,
  i.MGPrice,
  i.TOTAL,
  i.VAT,
  i.is_VAT,
  i.Status,
  i.VAT_TOTAL
FROM
  invoice i
LEFT JOIN
  services s1 ON CAST(i.SService1 AS UNSIGNED)  = s1.Service_ID
LEFT JOIN
  services s2 ON CAST(i.SService2 AS UNSIGNED)  = s2.Service_ID
LEFT JOIN
  services s3 ON CAST(i.SService3 AS UNSIGNED)  = s3.Service_ID
LEFT JOIN
  services s4 ON CAST(i.SService4 AS UNSIGNED)  = s4.Service_ID
LEFT JOIN
  services s5 ON CAST(i.SService5 AS UNSIGNED)  = s5.Service_ID;